spring:
  application:
    name: dtx-seata-bank1
  profiles:
    active: local

main:
  allow-bean-definition-overriding: true



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


server:
  servlet:
    context-path: /bank1



eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5    # \u7EED\u7EA6\u66F4\u65B0\u65F6\u95F4\u95F4\u9694\uFF08\u9ED8\u8BA430\u79D2\uFF09
    lease-expiration-duration-in-seconds: 10 # \u7EED\u7EA6\u5230\u671F\u65F6\u95F4\uFF08\u9ED8\u8BA490\u79D2\uFF09
  client:
    registry-fetch-interval-seconds: 5 # \u6293\u53D6\u670D\u52A1\u5217\u8868

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env


feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true # \u914D\u7F6E\u8BF7\u6C42GZIP\u538B\u7F29
      mime-types: ["text/xml","application/xml","application/json"] # \u914D\u7F6E\u538B\u7F29\u652F\u6301\u7684MIME TYPE
      min-request-size: 2048 # \u914D\u7F6E\u538B\u7F29\u6570\u636E\u5927\u5C0F\u7684\u4E0B\u9650
    response:
      enabled: true # \u914D\u7F6E\u54CD\u5E94GZIP\u538B\u7F29

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000  # \u8BBE\u7F6E\u7194\u65AD\u8D85\u65F6\u65F6\u95F4  default 1000
        timeout:
          enabled: true # \u6253\u5F00\u8D85\u65F6\u7194\u65AD\u529F\u80FD default true


ribbon:
  ConnectTimeout: 600 # \u8BBE\u7F6E\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4 default 2000
  ReadTimeout: 6000    # \u8BBE\u7F6E\u8BFB\u53D6\u8D85\u65F6\u65F6\u95F4  default 5000
  OkToRetryOnAllOperations: true # \u5BF9\u6240\u6709\u64CD\u4F5C\u8BF7\u6C42\u90FD\u8FDB\u884C\u91CD\u8BD5  default false
  MaxAutoRetriesNextServer: 2    # \u5207\u6362\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570  default 1
  MaxAutoRetries: 1     # \u5BF9\u5F53\u524D\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570 default 0